// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $career from "./routes/career.tsx";
import * as $index from "./routes/index.tsx";
import * as $ToggleTheme from "./islands/ToggleTheme.tsx";
import * as $Typewriter from "./islands/Typewriter.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/career.tsx": $career,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/ToggleTheme.tsx": $ToggleTheme,
    "./islands/Typewriter.tsx": $Typewriter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
